security:

    encoders:
        BlogBundle\Entity\Users:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: BlogBundle:Users
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
           anonymous: ~
           form_login:
                provider: db_provider
                login_path: login
                check_path: login_check
           logout:
                path: /logout
                target: /