<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;


/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{

    public function findAllByDate()
    {
        return $this->findBy(array(), array('added' => 'DESC'));
    }

    public function sortCatByDate($cat)
    {
        $em = $this->getDoctrine()->getManager();
        $query = $em->createQuery('
                SELECT p, c 
                FROM BlogBundle:Post p 
                JOIN p.category c 
                WHERE c.name = :cat
                ORDER BY p.added DESC
        ')->setParameter('cat', $cat);
        return $query->getResult();
    }

}
